Configure adaptive prop
GoogleChromeLabs/postcss-jit-props pull request #23
Opened 2022-10-08 19:32 UTC by mod3x

Hi!. 

Current implementation of adaptive prop (-@media:dark) contains characters that throws an not-valid syntax error on postcss compile step when props are parsed from css files not JSON. 
This PR adds a functionality to configure it.

Thank you.

2022-10-10 04:11 UTC, argyleink requested changes
thanks for this!

if i'm understanding correctly, this is introducing a new parameter `adaptive_prop_selector` to help developers avoid a parsing error? are you able to share a stackblitz or codesandbox that reproduce the issue? i havent seen it yet in vite, astro or a vanilla postcss config, so I'm curious and would like to see the full picture 🙂 

all in all though, it looks to be additive and non destructive to the current features. i appreciate you adding a test! 🤘🏻 given the problem scenario makes sense enough, this looks like it can merge soon 👍🏻

2022-10-10 04:11 UTC, argyleink commented on index.test.js
> +
could probably be reduced to just this yeah? less mock data to sift through to find what's being tested?

```suggestion
const MockPropsWithCustomAdaptiveProp = {
  '--text': 'white',
  '--text-dark': 'black',
}
```

2022-10-10 04:11 UTC, argyleink commented on index.test.js
> +}`,
can you shave these spacing edits from the PR please? will help focus the PR into only what's needing changed.

2022-10-10 04:11 UTC, argyleink commented on index.test.js
> +it('Can jit a light and dark with custom adaptive prop', async () => {
```suggestion
it('Can jit a light and dark color with a custom adaptive prop parameter', async () => {
```

is this suggestion the same as what you meant?

2022-10-20 20:27 UTC, mod3x commented
@argyleink heres [stackblitz demo](https://stackblitz.com/edit/node-8mv4sx?file=props.css)
package.json contains _postcss_ script to start compilation, thank you

2022-12-03 20:55 UTC, mod3x commented
>ty for the repro! looks like it's a bug in the CSS import feature specifically? that props using the naming convention break the CSS parser AND then don't get searched for. yeah?

Youre right.

>i'm almost thinking this means i need to change the syntax for these special props, so that they parse from CSS without any special configuration? it's like i missed this use case entirely in the tests and it's here to show the strategy needs adjusted

It would be cool. I mean its post**css** after all, align it with css spec as much as possible :)

2022-12-05 23:56 UTC, argyleink approved these changes
cool, looks good, ty!

2022-12-05 23:56 UTC, merged